-- DEPARTMENT TABLE
INSERT INTO DEPARTMENT (ID, DEPARTMENT_LABEL) VALUES (1, 'Accounting');
INSERT INTO DEPARTMENT (ID, DEPARTMENT_LABEL) VALUES (2, 'Sales');
INSERT INTO DEPARTMENT (ID, DEPARTMENT_LABEL) VALUES (3, 'IT');

-- EMPLOYEE TABLE
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (1, 'Bob', 15000, 1, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (2, 'Ted', 25000, 1, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (3, 'Sam', 7000, 1, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (4, 'Alice', 17000, 2, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (5, 'Tom', 20000, 2, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (6, 'Marylin', 23000, 2, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (7, 'Joe', 12000, 3, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (8, 'Anna', 23000, 3, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT_ID, LAST_UPDATE)
VALUES (9, 'John', 16000, 3, CURRENT_TIMESTAMP);